permalink: /posts/:year-:month-:day-:title.html

future: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
github:
  owner_url: https://github.com/BIDS/carpentries-club
url: https://BIDS.github.io/carpentries-club
name: The Berkeley Carpentries Club
chapter: Berkeley Institute for Data Science
description: BCC at BIDS
twitter: UCBIDS
avatar_url: /images/dats-logo.png
disqus_username: 

